version: '3.9'

services:
  golang_server:
    build:
      context: .
    restart: always
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - api_network

  db:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    env_file: .env
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:${DB_DATA}
    networks:
      - api_network
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data:

networks:
  api_network: